name = "formidi"
version = "0.3.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "2021-2024 Vincent Magnin"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir="src"

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

[[example]]
name = "third_kind"
source-dir = "example"
main = "third_kind.f90"

[[example]]
name = "canon"
source-dir = "example"
main = "canon.f90"

[[example]]
name = "blues"
source-dir = "example"
main = "blues.f90"

[[example]]
name = "circle_of_fifths"
source-dir = "example"
main = "circle_of_fifths.f90"

[[example]]
name = "la_folia"
source-dir = "example"
main = "la_folia.f90"

[[example]]
name = "motifs"
source-dir = "example"
main = "motifs.f90"
