checked_int32 – ForMIDI
checked_int32 Function
GNU Free Documentation License
11 statements
Source File
public function checked_int32(i) result(i32)
Receives a default kind integer, checks its bounds (Fortran signed int), fixes it if needed, and returns an int32.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Return Value integer(kind=int32)
Called by
Call graph
delta_time calls checked_int32
new calls checked_int32, set_tempo, end_of_track, set_time_signature, copyright_notice, text_event, track_header
play_broken_chord calls checked_int32, delta_time
play_chord calls checked_int32, delta_time
play_note calls checked_int32, delta_time
set_tempo calls checked_int32, delta_time
control_change calls delta_time
end_of_track calls delta_time
mono_aftertouch calls delta_time
pitch_bend calls delta_time
poly_aftertouch calls delta_time
program_change calls delta_time
set_time_signature calls delta_time
write_string calls delta_time
blues calls delta_time, new, play_chord, control_change, end_of_track, program_change, track_header
canon calls new, play_note, control_change, end_of_track, program_change, track_header
circle_of_fifths calls new, play_chord, control_change, end_of_track, program_change, track_header
la_folia calls new, play_broken_chord, play_chord, control_change, end_of_track, program_change, track_header
motifs calls new, play_broken_chord, play_chord, play_note, control_change, end_of_track, program_change, track_header
third_kind calls new, play_note, end_of_track, program_change, track_header
copyright_notice calls write_string
cue_point calls write_string
instrument_name calls write_string
lyric calls write_string
marker calls write_string
sequence_track_name calls write_string
text_event calls write_string
track_header calls sequence_track_name, text_event