checked_int8 – ForMIDI
checked_int8 Function
GNU Free Documentation License
18 statements
Source File
public function checked_int8(i, upper) result(i8)
Receives a default kind integer, checks its MIDI bounds (15 or 127), fixes it if needed, and returns an int8:
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
integer, intent(in), optional :: upper
Return Value integer(kind=int8)
Called by
Call graph
control_change calls checked_int8
mono_aftertouch calls checked_int8
new calls checked_int8, set_time_signature, copyright_notice, text_event, track_header
note_name calls checked_int8
note_off calls checked_int8
note_on calls checked_int8
pitch_bend calls checked_int8
poly_aftertouch calls checked_int8
program_change calls checked_int8
set_time_signature calls checked_int8
write_string calls checked_int8
copyright_notice calls write_string
cue_point calls write_string
instrument_name calls write_string
lyric calls write_string
marker calls write_string
play_broken_chord calls note_off, note_on
play_chord calls note_off, note_on
play_note calls note_off, note_on
sequence_track_name calls write_string
text_event calls write_string
blues calls control_change, new, note_off, note_on, program_change, play_chord, track_header
canon calls control_change, new, program_change, play_note, track_header
circle_of_fifths calls control_change, new, program_change, play_chord, track_header
la_folia calls control_change, new, program_change, play_broken_chord, play_chord, track_header
motifs calls control_change, new, program_change, play_broken_chord, play_chord, play_note, track_header
third_kind calls new, program_change, play_note, track_header
track_header calls sequence_track_name, text_event