Control_Change – ForMIDI
Control_Change Subroutine
GNU Free Documentation License
10 statements
Source File
public subroutine Control_Change(self, channel, type, ctl_value)
Many MIDI parameters can be set by Control Change. See the list.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: type
integer, intent(in) :: ctl_value
Calls
Called by
Call graph
control_change calls checked_int8, delta_time
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
blues calls control_change
canon calls control_change
circle_of_fifths calls control_change
la_folia calls control_change
motifs calls control_change