copyright_notice – ForMIDI
copyright_notice Subroutine
GNU Free Documentation License
5 statements
Source File
private subroutine copyright_notice(self, text)
Copyright Notice event: FF 02 len text
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: text
Calls
Called by
Call graph
copyright_notice calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity
new calls copyright_notice
blues calls new
canon calls new
circle_of_fifths calls new
la_folia calls new
third_kind calls new