delta_time – ForMIDI
delta_time Subroutine
GNU Free Documentation License
5 statements
Source File
public subroutine delta_time(self, ticks)
Each MIDI event must be preceded by a delay called "delta time", expressed in MIDI ticks.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: ticks
Calls
Called by
Call graph
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
control_change calls delta_time
end_of_track calls delta_time
mono_aftertouch calls delta_time
pitch_bend calls delta_time
play_broken_chord calls delta_time
play_chord calls delta_time
play_note calls delta_time
poly_aftertouch calls delta_time
program_change calls delta_time
set_tempo calls delta_time
set_time_signature calls delta_time
write_string calls delta_time
blues calls delta_time, control_change, end_of_track, play_chord, program_change, new, track_header
copyright_notice calls write_string
cue_point calls write_string
instrument_name calls write_string
lyric calls write_string
marker calls write_string
new calls end_of_track, set_tempo, set_time_signature, copyright_notice, text_event, track_header
sequence_track_name calls write_string
text_event calls write_string
canon calls control_change, end_of_track, play_note, program_change, new, track_header
circle_of_fifths calls control_change, end_of_track, play_chord, program_change, new, track_header
la_folia calls control_change, end_of_track, play_broken_chord, play_chord, program_change, new, track_header
motifs calls control_change, end_of_track, play_broken_chord, play_chord, play_note, program_change, new, track_header
third_kind calls end_of_track, play_note, program_change, new, track_header
track_header calls sequence_track_name, text_event