end_of_track – ForMIDI
end_of_track Subroutine
GNU Free Documentation License
10 statements
Source File
public subroutine end_of_track(self)
A track must end with 0xFF2F00.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
Calls
Called by
Call graph
end_of_track calls delta_time, write_track_size
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
new calls end_of_track
blues calls end_of_track, new
canon calls end_of_track, new
circle_of_fifths calls end_of_track, new
la_folia calls end_of_track, new
motifs calls end_of_track, new
third_kind calls end_of_track, new