get_name – ForMIDI
get_name Function
GNU Free Documentation License
5 statements
Source File
private function get_name(self)
Returns the name of the MIDI file:
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(in) :: self
Return Value character(len=len(self%filename))
Called by
Call graph
blues calls get_name
canon calls get_name
circle_of_fifths calls get_name
la_folia calls get_name
third_kind calls get_name