init_formidi – ForMIDI
init_formidi Subroutine
GNU Free Documentation License
7 statements
Source File
public subroutine init_formidi(self)
Verifies the needed data types.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(in) :: self
Called by
Call graph
new calls init_formidi
blues calls new
canon calls new
circle_of_fifths calls new
la_folia calls new
motifs calls new
third_kind calls new