instrument_name – ForMIDI
instrument_name Subroutine
GPL
5 statements
Source File
private subroutine instrument_name(self, text)
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: text
Calls
Call graph
instrument_name calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity