lyric – ForMIDI
lyric Subroutine
GNU Free Documentation License
5 statements
Source File
public subroutine lyric(self, text)
Lyric event: FF 05 len text
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: text
Calls
Call graph
lyric calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity