new – ForMIDI
new Subroutine
GPL
52 statements
Source File
private subroutine new(self, file_name, format, tracks, divisions, tempo, time_signature, copyright, text_event)
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: file_name
integer, intent(in) :: format
integer, intent(in) :: tracks
integer, intent(in) :: divisions
integer, intent(in) :: tempo
integer, intent(in), optional :: time_signature(:)
character(len=*), intent(in), optional :: copyright
character(len=*), intent(in), optional :: text_event
Calls
Called by
Call graph
new calls checked_int16, checked_int32, checked_int8, copyright_notice, end_of_track, init_formidi, set_tempo, set_time_signature, text_event, track_header
copyright_notice calls write_string
end_of_track calls delta_time, write_track_size
set_tempo calls checked_int32, delta_time
set_time_signature calls checked_int8, delta_time
text_event calls write_string
track_header calls text_event, sequence_track_name
delta_time calls checked_int32, write_variable_length_quantity
sequence_track_name calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
blues calls new
canon calls new
circle_of_fifths calls new
la_folia calls new
third_kind calls new