Note_ON – ForMIDI
Note_ON Subroutine
GPL
9 statements
Source File
private subroutine Note_ON(self, channel, note, velocity)
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: note
integer, intent(in) :: velocity
Calls
Called by
Source Code
    subroutine Note_ON(self, channel, note, velocity)
        class(MIDI_file), intent(inout) :: self
        integer, intent(in) :: channel, note, velocity    ! 8 bits
        integer(int8) :: octets(0:2)
        octets(0) = ON + checked_int8(channel, upper=15)
        octets(1) = checked_int8(note)
        octets(2) = checked_int8(velocity)
        write(self%unit, iostat=self%status) octets
    end subroutine Note_ON
Call graph
note_on calls checked_int8
play_broken_chord calls note_on
play_chord calls note_on
play_note calls note_on
blues calls note_on, play_chord
canon calls play_note
circle_of_fifths calls play_chord
la_folia calls play_broken_chord, play_chord
third_kind calls play_note