play_chord – ForMIDI
play_chord Subroutine
GPL
17 statements
Source File
private subroutine play_chord(self, channel, note, chord, velocity, value)
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: note
integer, intent(in), dimension(:) :: chord
integer, intent(in) :: velocity
integer, intent(in) :: value
Calls
Called by
Call graph
play_chord calls checked_int32, delta_time, note_off, note_on
delta_time calls checked_int32, write_variable_length_quantity
note_off calls checked_int8
note_on calls checked_int8
write_variable_length_quantity calls variable_length_quantity
blues calls play_chord
circle_of_fifths calls play_chord
la_folia calls play_chord