play_note – ForMIDI
play_note Subroutine
GNU Free Documentation License
9 statements
Source File
private subroutine play_note(self, channel, note, velocity, value)
Write a Note ON event, waits for its duration, and writes a Note OFF.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: note
integer, intent(in) :: velocity
integer, intent(in) :: value
Calls
Called by
Call graph
play_note calls checked_int32, delta_time, note_off, note_on
delta_time calls checked_int32, write_variable_length_quantity
note_off calls checked_int8
note_on calls checked_int8
write_variable_length_quantity calls variable_length_quantity
canon calls play_note
third_kind calls play_note