poly_aftertouch – ForMIDI
poly_aftertouch Subroutine
GNU Free Documentation License
10 statements
Source File
public subroutine poly_aftertouch(self, channel, note, pressure)
Writes a polyphonic key pressure (poly aftertouch) event. The pressure is in the range 0..127.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: note
integer, intent(in) :: pressure
Calls
Source Code
    subroutine poly_aftertouch(self, channel, note, pressure)
        class(MIDI_file), intent(inout) :: self
        integer, intent(in) :: channel, note, pressure    ! 8 bits
        integer(int8) :: octets(0:2)
        call self%delta_time(0)
        octets(0) = int(z'A0', int8) + checked_int8(channel, upper=15)
        octets(1) = checked_int8(note)
        octets(2) = checked_int8(pressure)
        write(self%unit, iostat=self%status) octets
    end subroutine poly_aftertouch
Call graph
poly_aftertouch calls checked_int8, delta_time
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity