Program_Change – ForMIDI
Program_Change Subroutine
GNU Free Documentation License
9 statements
Source File
public subroutine Program_Change(self, channel, instrument)
Each channel (0..15) can use one General MIDI instrument (0..127) at a time.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: channel
integer, intent(in) :: instrument
Calls
Called by
Call graph
program_change calls checked_int8, delta_time
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
blues calls program_change
canon calls program_change
circle_of_fifths calls program_change
la_folia calls program_change
motifs calls program_change
third_kind calls program_change