sequence_track_name – ForMIDI
sequence_track_name Subroutine
GPL
5 statements
Source File
private subroutine sequence_track_name(self, text)
Sequence or Track Name event: FF 03 len text
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: text
Calls
Called by
Call graph
sequence_track_name calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity
track_header calls sequence_track_name
new calls track_header
blues calls track_header, new
canon calls track_header, new
circle_of_fifths calls track_header, new
la_folia calls track_header, new
third_kind calls track_header, new