set_tempo – ForMIDI
set_tempo Subroutine
GNU Free Documentation License
15 statements
Source File
public subroutine set_tempo(self, duration)
Specifies a tempo change by writing the duration of a quarter note expressed in µs. It is coded on 3 bytes: from 1 µs to 256**3 µs ~ 16.7 s. A duration of 500000 µs = 0.5 s is equivalent to a 120 bpm tempo. https://en.wikipedia.org/wiki/Tempo MIDI events must always be preceded by a "delta time", even if null:
Metadata always begin by 0xFF. Here, these codes mean we will define the music tempo:
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: duration
Calls
Called by
Call graph
set_tempo calls checked_int32, delta_time
delta_time calls checked_int32, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity
new calls set_tempo
blues calls new
canon calls new
circle_of_fifths calls new
la_folia calls new
motifs calls new
third_kind calls new