text_event – ForMIDI
text_event Subroutine
GNU Free Documentation License
5 statements
Source File
public subroutine text_event(self, text)
Text event: FF 01 len text
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in) :: text
Calls
Called by
Call graph
text_event calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity
new calls text_event, track_header
track_header calls text_event
blues calls new, track_header
canon calls new, track_header
circle_of_fifths calls new, track_header
la_folia calls new, track_header
motifs calls new, track_header
third_kind calls new, track_header