track_header – ForMIDI
track_header Subroutine
GNU Free Documentation License
19 statements
Source File
public subroutine track_header(self, track_name, text_event)
Writes a track header and stores the position where the size of the track will be written when the track will be closed.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
character(len=*), intent(in), optional :: track_name
character(len=*), intent(in), optional :: text_event
Calls
Called by
Call graph
track_header calls sequence_track_name, text_event
sequence_track_name calls write_string
text_event calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity
new calls track_header
blues calls track_header, new
canon calls track_header, new
circle_of_fifths calls track_header, new
la_folia calls track_header, new
motifs calls track_header, new
third_kind calls track_header, new