write_track_size – ForMIDI
write_track_size Subroutine
GNU Free Documentation License
14 statements
Source File
public subroutine write_track_size(self)
Must be called when the track is finished. It writes its size at the memorized position in the track header.
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
Called by
Call graph
end_of_track calls write_track_size
new calls end_of_track
blues calls end_of_track, new
canon calls end_of_track, new
circle_of_fifths calls end_of_track, new
la_folia calls end_of_track, new
motifs calls end_of_track, new
third_kind calls end_of_track, new