write_string – ForMIDI
write_string Subroutine
GNU Free Documentation License
15 statements
Source File
public subroutine write_string(self, event, text)
This subroutine is used my many events. The text must be coded in ASCII (7 bits).
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer, intent(in) :: event
character(len=*), intent(in) :: text
Calls
Called by
Call graph
write_string calls checked_int8, delta_time, write_variable_length_quantity
delta_time calls write_variable_length_quantity, checked_int32
write_variable_length_quantity calls variable_length_quantity
copyright_notice calls write_string
cue_point calls write_string
instrument_name calls write_string
lyric calls write_string
marker calls write_string
sequence_track_name calls write_string
text_event calls write_string
new calls copyright_notice, text_event, track_header
track_header calls sequence_track_name, text_event
blues calls new, track_header
canon calls new, track_header
circle_of_fifths calls new, track_header
la_folia calls new, track_header
motifs calls new, track_header
third_kind calls new, track_header