write_variable_length_quantity – ForMIDI
write_variable_length_quantity Subroutine
GNU Free Documentation License
14 statements
Source File
public subroutine write_variable_length_quantity(self, i)
Writes the integer i in the MIDI file using the variable length quantity representation:
Type Bound
MIDI_file
Arguments
Type Intent Optional Attributes Name
class(MIDI_file), intent(inout) :: self
integer(kind=int32), intent(in) :: i
Calls
Called by
Source Code
    subroutine write_variable_length_quantity(self, i)
        class(MIDI_file), intent(inout) :: self
        integer(int32), intent(in) :: i
        integer(int32) :: j
        integer(int8), allocatable, dimension(:) :: array
        ! The maximum possible MIDI value:
        if (i > int(z'0FFFFFFF', int32)) then
            write(error_unit, *) "ERROR 2: delay > 0x0FFFFFFF ! ", i
            error stop 2
        end if
        array = variable_length_quantity(i)
        ! The bytes are now written in the file:
        do j = 1, size(array)
            write(self%unit, iostat=self%status) array(j)
        end do
    end subroutine write_variable_length_quantity
Call graph
write_variable_length_quantity calls variable_length_quantity
delta_time calls write_variable_length_quantity
write_string calls write_variable_length_quantity, delta_time
control_change calls delta_time
copyright_notice calls write_string
cue_point calls write_string
end_of_track calls delta_time
instrument_name calls write_string
lyric calls write_string
marker calls write_string
mono_aftertouch calls delta_time
pitch_bend calls delta_time
play_broken_chord calls delta_time
play_chord calls delta_time
play_note calls delta_time
poly_aftertouch calls delta_time
program_change calls delta_time
sequence_track_name calls write_string
set_tempo calls delta_time
set_time_signature calls delta_time
text_event calls write_string
blues calls delta_time, control_change, end_of_track, play_chord, program_change, new, track_header
new calls copyright_notice, end_of_track, set_tempo, set_time_signature, text_event, track_header
track_header calls sequence_track_name, text_event
canon calls control_change, end_of_track, play_note, program_change, new, track_header
circle_of_fifths calls control_change, end_of_track, play_chord, program_change, new, track_header
la_folia calls control_change, end_of_track, play_broken_chord, play_chord, program_change, new, track_header
motifs calls control_change, end_of_track, play_broken_chord, play_chord, play_note, program_change, new, track_header
third_kind calls end_of_track, play_note, program_change, new, track_header