canon – ForMIDI
canon Program
GNU Free Documentation License
42 statements
Source File
Uses
MIDI_file_class
MIDI_control_changes
music
GM_instruments
An example based on the first measures of Pachelbel's Canon https://en.wikipedia.org/wiki/Pachelbel%27s_Canon
Calls
Variables
Type Attributes Name Initial
character(len=3), parameter :: bass(1:8) = ["D3 ", "A2 ", "B2 ", "F#2", "G2 ", "D2 ", "G2 ", "A2 "]
integer :: i
integer, parameter :: instrument(1:17) = [40, 41, 42, 44, 45, 48, 49, 51, 52, 89, 90, 91, 92, 94, 95, 99, 100]
integer :: j
type(MIDI_file) :: midi
integer, parameter :: panning(2:5) = [54, 34, 74, 94]
character(len=3), parameter :: theme(1:16) = ["F#5", "E5 ", "D5 ", "C#5", "B4 ", "A4 ", "B4 ", "C#5", "D5 ", "C#5", "B4 ", "A4 ", "G4 ", "F#4", "G4 ", "E4 "]
integer :: track
character(len=13) :: track_name
Source Code
program canon
    use MIDI_file_class
    use music
    use MIDI_control_changes, only: Effects_1_Depth, Pan
    ! Contains the list of General MIDI 128 instruments and 47 percussions:
    use GM_instruments
    implicit none
    type(MIDI_file) :: midi
    ! Notes of the bass and theme:
    character(3), parameter :: bass(1:8) =  ["D3 ","A2 ","B2 ","F#2","G2 ", &
                                            &"D2 ","G2 ","A2 " ]
    character(3), parameter :: theme(1:16) = [ "F#5","E5 ","D5 ","C#5", &
                                             & "B4 ","A4 ","B4 ","C#5", &
                                             & "D5 ","C#5","B4 ","A4 ", &
                                             & "G4 ","F#4","G4 ","E4 " ]
    ! List of General MIDI instruments to use sequentially:
    integer, parameter :: instrument(1:17) = [ 40, 41, 42, 44, 45, 48,&
                                 & 49, 51, 52, 89, 90, 91, 92, 94, 95, 99, 100 ]
    ! Pan value for each track:
    integer, parameter :: panning(2:5) = [ 54, 34, 74, 94 ]
    integer :: track
    character(13) :: track_name
    integer :: i, j
    ! Create a file with 5 tracks (including the metadata track):
    ! A quarter note will last 1000000 s = 1 s => tempo = 60 bpm
    call midi%new("canon.mid", format=1, tracks=5, divisions=quarter_note, tempo=1000000, copyright="Public domain")
    ! (1) A first music track: ground bass
    call midi%track_header(track_name="ground bass")
    call midi%Control_Change(channel=0, type=Effects_1_Depth, ctl_value=64)  ! Reverb
    ! Instrument on channel 0:
    call midi%Program_Change(channel=0, instrument=String_Ensemble_1)
    ! Panning:
    call midi%Control_Change(channel=0, type=Pan, ctl_value=panning(2))
    do j = 1, 30
        do i = 1, 8
            call midi%play_note(channel=0, note=MIDI_Note(bass(i)), velocity=mf_level, value=quarter_note)
        end do
    end do
    call midi%end_of_track()
    ! Three other music tracks: a three voices canon with various instruments
    do track = 3, 5
        write(track_name, '("Canon voice ",I0)') track-2
        call midi%track_header(track_name)
        ! Reverb and pan:
        call midi%Control_Change(channel=track, type=Effects_1_Depth, ctl_value=64)
        call midi%Control_Change(channel=track, type=Pan, ctl_value=panning(track))
        ! A pause to shift the start of each voice of the canon:
        call midi%play_note(channel=track, note=0, velocity=0, value=8*quarter_note*(track - 2))
        do j = 1, 15
            ! Let's change regularly the instruments to add some variations:
            call midi%Program_Change(channel=track, instrument=instrument((track - 3) + j))
            ! Let's play the theme:
            do i = 1, 16
                call midi%play_note(channel=track, note=MIDI_Note(theme(i)), velocity=mf_level, value=quarter_note)
            end do
        end do
        call midi%end_of_track()
    end do
    call midi%close()
    print *,"You can now play the file ", midi%get_name()
end program canon
Call graph
canon calls control_change, end_of_track, get_name, midi_note, new, play_note, program_change, track_header
control_change calls checked_int8, delta_time
end_of_track calls delta_time, write_track_size
new calls end_of_track, track_header, checked_int16, checked_int32, checked_int8, copyright_notice, init_formidi, set_tempo, set_time_signature, text_event
play_note calls checked_int32, delta_time, note_off, note_on
program_change calls checked_int8, delta_time
track_header calls sequence_track_name, text_event
copyright_notice calls write_string
delta_time calls checked_int32, write_variable_length_quantity
note_off calls checked_int8
note_on calls checked_int8
sequence_track_name calls write_string
set_tempo calls checked_int32, delta_time
set_time_signature calls checked_int8, delta_time
text_event calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity