circle_of_fifths – ForMIDI
circle_of_fifths Program
GPL
51 statements
Source File
Uses
iso_fortran_env
MIDI_control_changes
music
MIDI_file_class
GM_instruments
A random walk on the circle of fifths
Calls
Variables
Type Attributes Name Initial
integer :: channel
integer :: i
integer :: instrument
integer, parameter :: length = 200
logical :: major
type(MIDI_file) :: midi
character(len=3) :: name
integer :: note
real(kind=dp) :: p
integer :: velocity
Source Code
program circle_of_fifths
    use, intrinsic :: iso_fortran_env, only: dp=>real64
    use MIDI_file_class
    use music
    use MIDI_control_changes, only: Effects_1_Depth
    ! Contains the list of General MIDI 128 instruments and 47 percussions:
    use GM_instruments
    implicit none
    type(MIDI_file) :: midi
    integer :: channel, instrument, velocity, note
    character(3) :: name
    logical  :: major
    integer, parameter :: length = 200
    integer  :: i
    real(dp) :: p
    ! Create a file with 2 tracks (including the metadata track):
    ! The first track is always a metadata track. We define the
    ! tempo: a quarter note will last 500000 s = 0.5 s => tempo = 120 bpm
    call midi%new("circle_of_fifths.mid", format=1, tracks=2, divisions=quarter_note, tempo=500000)
    ! (1) The single music track:
    call midi%track_header()
    ! Sounds also good with instruments String_Ensemble_2 and Pad_8_sweep:
    instrument = Choir_Aahs
    ! We will use altenatively MIDI channels 0 and 1 to avoid cutting
    ! the tail of each chord:
    call midi%Program_Change(channel=0, instrument=instrument)
    call midi%Program_Change(channel=1, instrument=instrument)
    ! Heavy (127) reverb effect:
    call midi%Control_Change(channel=0, type=Effects_1_Depth, ctl_value=127)  ! Reverb
    call midi%Control_Change(channel=1, type=Effects_1_Depth, ctl_value=127)  ! Reverb
    ! We start with C Major (note at the top of the Major circle):
    note = 1
    major = .true.
    name = trim(CIRCLE_OF_FIFTHS_MAJOR(note)) // "4"
    call midi%play_chord(channel=0, note=MIDI_Note(name), chord=MAJOR_CHORD, velocity=f_level+10, value=whole_note)
    ! A random walk with three events: we can go one note clockwise,
    ! one note counterclockwise or switch Major<->minor.
    do i = 1, length
        ! A random number 0 <= p < 3
        call random_number(p)
        p = 3 * p
        ! The three possible events:
        if (p >= 2.0_dp) then
            note = note + 1
            if (note > 12) note = 1
        else if (p >= 1.0_dp) then
            note = note - 1
            if (note < 1) note = 12
        else
            major = .not. major
        end if
        ! Alternate between channels 0 and 1:
        channel = mod(i, 2)
        ! The volume will evolve, to obtain some dynamics:
        velocity = f_level + 10 + int(20*sin(real(i)))
        ! Write a major or minor chord on the track:
        if (major) then
            name = trim(CIRCLE_OF_FIFTHS_MAJOR(note)) // "4"
            call midi%play_chord(channel, MIDI_Note(name), MAJOR_CHORD, velocity, whole_note)
        else
            name = trim(CIRCLE_OF_FIFTHS_MINOR(note)) // "4"
            call midi%play_chord(channel, MIDI_Note(name), MINOR_CHORD, velocity, whole_note)
        end if
    end do
    call midi%end_of_track()
    call midi%close()
    print *,"You can now play the file ", midi%get_name()
end program circle_of_fifths
Call graph
circle_of_fifths calls control_change, end_of_track, get_name, midi_note, new, play_chord, program_change, track_header
control_change calls checked_int8, delta_time
end_of_track calls delta_time, write_track_size
new calls end_of_track, track_header, checked_int16, checked_int32, checked_int8, copyright_notice, init_formidi, set_tempo, set_time_signature, text_event
play_chord calls checked_int32, delta_time, note_off, note_on
program_change calls checked_int8, delta_time
track_header calls sequence_track_name, text_event
copyright_notice calls write_string
delta_time calls checked_int32, write_variable_length_quantity
note_off calls checked_int8
note_on calls checked_int8
sequence_track_name calls write_string
set_tempo calls checked_int32, delta_time
set_time_signature calls checked_int8, delta_time
text_event calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity