third_kind – ForMIDI
third_kind Program
GPL
18 statements
Source File
Uses
GM_instruments
MIDI_file_class
music
Calls
Variables
Type Attributes Name Initial
type(MIDI_file) :: midi
Source Code
program third_kind
    ! The main class you need to create music:
    use MIDI_file_class
    ! The function MIDI_Note() returns the MIDI number of a note from 12 (C0)
    ! to 127 (G9). The A4 (440 Hz tuning standard) is the note 69.
    use music
    ! Contains the list of General MIDI 128 instruments and 47 percussions:
    use GM_instruments
    implicit none
    type(MIDI_file) :: midi
    ! You will generally use the format SMF 1 which allows several tracks
    ! to be played together.
    ! We will use only one musical track but we need 2 tracks, as there is
    ! always a metadata track automatically created by the new() method.
    ! Divisions is the number of ticks ("metrical timing" MIDI scheme) in
    ! a quarter note, and can be considered as the time resolution of your file.
    ! We define the tempo: a quarter note will last 500000 s = 0.5 s => tempo=120 bpm
    call midi%new("third_kind.mid", format=1, tracks=2, divisions=quarter_note, tempo=500000, &
                & text_event="This file was created with the ForMIDI Fortran project")
    ! (1) The single musical track:
    call midi%track_header()
    ! Choosing the instrument (in the 0..127 range):
    call midi%Program_Change(channel=0, instrument=Pad_6_metallic)
    ! Playing a sequence of five notes on MIDI channel 0:
    call midi%play_note(channel=0, note=MIDI_Note("G4"), velocity=mf_level, value=quarter_note)
    call midi%play_note(channel=0, note=MIDI_Note("A4"), velocity=mf_level, value=quarter_note)
    call midi%play_note(channel=0, note=MIDI_Note("F4"), velocity=mf_level, value=quarter_note)
    call midi%play_note(channel=0, note=MIDI_Note("F3"), velocity=mf_level, value=quarter_note)
    call midi%play_note(channel=0, note=MIDI_Note("C4"), velocity=mf_level, value=half_note)
    ! The MIDI velocity is the speed at which you type on the keyboard and
    ! can be considered equivalent to the volume. As many MIDI values, it is
    ! defined in the 0..127 range.
    ! There are 16 channels (0..15).
    ! The value (duration) of a note is expressed in MIDI ticks.
    call midi%end_of_track()
    call midi%close()
    print *,"You can now play the file ", midi%get_name()
end program third_kind
Call graph
third_kind calls end_of_track, get_name, midi_note, new, play_note, program_change, track_header
end_of_track calls delta_time, write_track_size
new calls end_of_track, track_header, checked_int16, checked_int32, checked_int8, copyright_notice, init_formidi, set_tempo, set_time_signature, text_event
play_note calls checked_int32, delta_time, note_off, note_on
program_change calls checked_int8, delta_time
track_header calls sequence_track_name, text_event
copyright_notice calls write_string
delta_time calls checked_int32, write_variable_length_quantity
note_off calls checked_int8
note_on calls checked_int8
sequence_track_name calls write_string
set_tempo calls checked_int32, delta_time
set_time_signature calls checked_int8, delta_time
text_event calls write_string
write_string calls checked_int8, delta_time, write_variable_length_quantity
write_variable_length_quantity calls variable_length_quantity